"""Machine-discoverable public CLI capabilities."""

from __future__ import annotations

from typing import Any

from .templates import PROJECT_TEMPLATE_IDS


EXIT_CODES = {"success": 0, "failure": [1], "usage": 2}


def argument(
    name: str,
    form: str,
    value: str,
    required: bool,
    description: str,
    *,
    default: Any | None = None,
    choices: list[str] | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "name": name,
        "form": form,
        "value": value,
        "required": required,
        "description": description,
    }
    if default is not None:
        result["default"] = default
    if choices is not None:
        result["choices"] = choices
    return result


JSON_ARGUMENT = argument(
    "json",
    "option",
    "boolean",
    False,
    "Emit one versioned machine-readable JSON envelope.",
    default=False,
)
PROJECT_ARGUMENT = argument(
    "project",
    "option",
    "string",
    False,
    "Project id inside a Workspace.",
    default="Workspace default",
)
PATH_ARGUMENT = argument(
    "path",
    "positional",
    "string",
    True,
    "Direct Project or Workspace directory.",
)
STUDY_ARGUMENT = argument(
    "study",
    "option",
    "string",
    True,
    "Project-local Study id.",
)
RUN_ARGUMENT = argument(
    "run",
    "option",
    "string",
    True,
    "Immutable Run id.",
)
SESSION_ARGUMENT = argument(
    "session",
    "option",
    "string",
    True,
    "Project-local research Session id.",
)
EXPERIMENT_ARGUMENT = argument(
    "experiment",
    "option",
    "string",
    True,
    "Immutable Experiment id inside a Session.",
)
CAMPAIGN_ARGUMENT = argument(
    "campaign",
    "option",
    "string",
    True,
    "Immutable Campaign id inside a Session.",
)
REPORT_ARGUMENT = argument(
    "report",
    "option",
    "string",
    True,
    "Immutable Research Report id inside a Session.",
)


def descriptor(
    command_id: str,
    usage: str,
    description: str,
    effect: str,
    arguments: list[dict[str, Any]],
    *,
    supports_json: bool = True,
) -> dict[str, Any]:
    return {
        "id": command_id,
        "usage": usage,
        "description": description,
        "effect": effect,
        "supportsJson": supports_json,
        "exitCodes": EXIT_CODES,
        "arguments": arguments,
        "outputSections": [],
    }


CLI_COMMANDS = [
    descriptor(
        "capabilities",
        "aq capabilities [--json]",
        "Describe every public command, argument, effect, and exit behavior.",
        "read-only",
        [JSON_ARGUMENT],
    ),
    descriptor(
        "schema",
        "aq schema [workspace|project|study|judge-output|run-result|session|experiment|research-request|report-analysis|researcher-response|campaign-result|campaign-progress|studio-snapshot] [--json]",
        "List or emit canonical AutoQuant JSON Schemas.",
        "read-only",
        [
            argument(
                "kind",
                "positional",
                "string",
                False,
                "Schema kind; omit to list kinds.",
                choices=[
                    "workspace",
                    "project",
                    "study",
                    "judge-output",
                    "run-result",
                    "session",
                    "experiment",
                    "researcher-response",
                    "campaign-result",
                    "campaign-progress",
                    "research-request",
                    "report-analysis",
                    "studio-snapshot",
                ],
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "workspace.init",
        "aq workspace init <workspace-dir> [--name NAME] [--json]",
        "Create an empty multi-Project AutoQuant Workspace.",
        "creates-artifact",
        [
            argument(
                "workspace-dir",
                "positional",
                "string",
                True,
                "New empty Workspace directory.",
            ),
            argument(
                "name",
                "option",
                "string",
                False,
                "Workspace display name.",
                default="Directory name",
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "project.create",
        "aq project create <workspace-dir> <project-id> [options]",
        "Create one complete self-contained quantitative research Project.",
        "creates-artifact",
        [
            argument(
                "workspace-dir",
                "positional",
                "string",
                True,
                "Existing AutoQuant Workspace directory.",
            ),
            argument(
                "project-id",
                "positional",
                "string",
                True,
                "Lowercase kebab-case Project id.",
            ),
            argument(
                "name",
                "option",
                "string",
                False,
                "Project display name.",
                default="Project id",
            ),
            argument(
                "description",
                "option",
                "string",
                False,
                "Initial quantitative research question.",
                default="Empty",
            ),
            argument(
                "template",
                "option",
                "string",
                False,
                "Self-contained Project construction template.",
                default="blank",
                choices=list(PROJECT_TEMPLATE_IDS),
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "project.list",
        "aq project list <workspace-dir> [--json]",
        "List immediate self-contained Workspace Projects.",
        "read-only",
        [
            argument(
                "workspace-dir",
                "positional",
                "string",
                True,
                "Existing AutoQuant Workspace directory.",
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "project.default",
        "aq project default <workspace-dir> <project-id> [--json]",
        "Select the Workspace default Project.",
        "mutates-workspace",
        [
            argument(
                "workspace-dir",
                "positional",
                "string",
                True,
                "Existing AutoQuant Workspace directory.",
            ),
            argument(
                "project-id",
                "positional",
                "string",
                True,
                "Existing Project id.",
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "validate",
        "aq validate <project-or-workspace-dir> [--project ID] [--json]",
        "Strictly validate and resolve one AutoQuant Project.",
        "read-only",
        [
            argument(
                "path",
                "positional",
                "string",
                True,
                "Direct Project or Workspace directory.",
            ),
            PROJECT_ARGUMENT,
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "inspect",
        "aq inspect <project-or-workspace-dir> [--project ID] [--json]",
        "Inspect one Project's research program and owned construction surfaces.",
        "read-only",
        [
            argument(
                "path",
                "positional",
                "string",
                True,
                "Direct Project or Workspace directory.",
            ),
            PROJECT_ARGUMENT,
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "study.create",
        "aq study create <path> <study-id> [contract options] [--json]",
        "Create and validate one fixed Project-local quantitative Study.",
        "creates-artifact",
        [
            PATH_ARGUMENT,
            argument(
                "study-id",
                "positional",
                "string",
                True,
                "Lowercase kebab-case Study id.",
            ),
            PROJECT_ARGUMENT,
            argument("name", "option", "string", False, "Study display name.", default="Study id"),
            argument("description", "option", "string", False, "Bounded research question.", default="Empty"),
            argument(
                "subject-kind",
                "option",
                "string",
                True,
                "Research subject kind.",
                choices=["strategy", "factor", "model", "research"],
            ),
            argument("subject-name", "option", "string", False, "Research subject name.", default="Study id"),
            argument("subject-version", "option", "string", False, "Mutable subject version label.", default="working"),
            argument("judge", "option", "string", True, "Project-relative Python Judge entrypoint."),
            argument("judge-path", "option", "string", False, "Repeatable fixed Judge file or trailing /** closure.", default="Judge entrypoint"),
            argument("judge-arg", "option", "string", False, "Repeatable fixed Judge argument.", default="None"),
            argument("editable", "option", "string", True, "Repeatable Agent-editable file or trailing /** closure."),
            argument("metric", "option", "string", False, "Primary metric name.", default="score"),
            argument(
                "direction",
                "option",
                "string",
                False,
                "Primary metric direction.",
                default="maximize",
                choices=["maximize", "minimize"],
            ),
            argument("minimum-improvement", "option", "number", False, "Minimum comparable improvement.", default=0),
            argument("dataset-id", "option", "string", True, "Dataset identity."),
            argument("dataset-version", "option", "string", False, "Dataset version.", default="working"),
            argument(
                "dataset-path",
                "option",
                "string",
                False,
                "Repeatable Project-data-relative file or trailing /** closure to content-lock.",
                default="Declarative dataset identity only",
            ),
            argument("asset-class", "option", "string", True, "Dataset asset class."),
            argument("asset", "option", "string", True, "Repeatable asset universe member."),
            argument("start", "option", "string", True, "Dataset start date YYYY-MM-DD."),
            argument("end", "option", "string", True, "Dataset end date YYYY-MM-DD."),
            argument("timeout", "option", "integer", False, "Judge timeout in seconds.", default=60),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "study.list",
        "aq study list <path> [--project ID] [--json]",
        "List strict Project-local Studies.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "study.inspect",
        "aq study inspect <path> --study ID [--project ID] [--json]",
        "Inspect one fixed Study, source closure, Judge, dataset, and input identity.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, STUDY_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "run.execute",
        "aq run execute <path> --study ID [--project ID] [--json]",
        "Execute one bounded Python Judge and publish an immutable RunResult.",
        "creates-artifact",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, STUDY_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "run.list",
        "aq run list <path> [--study ID] [--project ID] [--json]",
        "List verified immutable Runs, optionally filtered by Study.",
        "read-only",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            argument("study", "option", "string", False, "Optional Study id filter."),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "run.show",
        "aq run show <path> --run ID [--project ID] [--json]",
        "Verify and inspect one immutable RunResult.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, RUN_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "session.start",
        "aq session start <path> --study ID [--request FILE] [--project ID] [--json]",
        "Create a resumable candidate worktree and optionally bind one delegated Research Request into its fixed brief.",
        "creates-artifact",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            STUDY_ARGUMENT,
            argument(
                "request",
                "option",
                "string",
                False,
                "Strict research-request JSON supplied by OpenAlice or a local caller.",
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "session.list",
        "aq session list <path> [--project ID] [--json]",
        "List Project-local governed research Sessions.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "session.show",
        "aq session show <path> --session ID [--project ID] [--json]",
        "Inspect a Session Agent brief, authority, candidate, leader, and history.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, SESSION_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "session.promote",
        "aq session promote <path> --session ID [--project ID] [--json]",
        "Hash-check and promote the exact current KEEP into an unchanged Project base.",
        "mutates-project",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, SESSION_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "experiment.evaluate",
        "aq experiment evaluate <path> --session ID --hypothesis TEXT [--project ID] [--json]",
        "Evaluate the current worktree candidate and publish KEEP, REVERT, or CRASH evidence.",
        "creates-artifact",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            SESSION_ARGUMENT,
            argument(
                "hypothesis",
                "option",
                "string",
                True,
                "Falsifiable description of the candidate change.",
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "experiment.list",
        "aq experiment list <path> --session ID [--project ID] [--json]",
        "List immutable Experiment history for one Session.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, SESSION_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "experiment.show",
        "aq experiment show <path> --session ID --experiment ID [--project ID] [--json]",
        "Verify and inspect one immutable Experiment, source change set, and candidate Run.",
        "read-only",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            SESSION_ARGUMENT,
            EXPERIMENT_ARGUMENT,
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "research.run",
        "aq research run <path> --session ID --agent-command SHELL [budgets] [--project ID] [--json]",
        "Run a user-authorized external shell Researcher against one governed Session and publish immutable Campaign evidence.",
        "creates-artifact",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            SESSION_ARGUMENT,
            argument(
                "agent-command",
                "option",
                "string",
                True,
                "Explicit host shell command receiving a turn brief on stdin.",
            ),
            argument(
                "max-turns",
                "option",
                "integer",
                False,
                "Maximum Researcher turns.",
                default=5,
            ),
            argument(
                "max-wall-seconds",
                "option",
                "integer",
                False,
                "Aggregate Campaign wall-clock budget.",
                default=900,
            ),
            argument(
                "turn-timeout-seconds",
                "option",
                "integer",
                False,
                "Maximum duration of one Researcher command.",
                default=300,
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "research.list",
        "aq research list <path> --session ID [--project ID] [--json]",
        "List verified immutable Researcher Campaigns in one Session.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, SESSION_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "research.show",
        "aq research show <path> --session ID --campaign ID [--project ID] [--json]",
        "Verify and inspect one immutable Campaign and its turn evidence.",
        "read-only",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            SESSION_ARGUMENT,
            CAMPAIGN_ARGUMENT,
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "report.publish",
        "aq report publish <path> --session ID --analysis FILE [--project ID] [--json]",
        "Verify Agent-authored analysis references and publish immutable JSON plus Markdown over one delegated Session evidence snapshot.",
        "creates-artifact",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            SESSION_ARGUMENT,
            argument(
                "analysis",
                "option",
                "string",
                True,
                "Strict report-analysis JSON with evidence-bound findings.",
            ),
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "report.list",
        "aq report list <path> --session ID [--project ID] [--json]",
        "List verified immutable Research Reports in one Session.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, SESSION_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "report.show",
        "aq report show <path> --session ID --report ID [--project ID] [--json]",
        "Verify and inspect one immutable evidence-bound Research Report.",
        "read-only",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            SESSION_ARGUMENT,
            REPORT_ARGUMENT,
            JSON_ARGUMENT,
        ],
    ),
    descriptor(
        "studio.snapshot",
        "aq studio snapshot <path> [--project ID] [--json]",
        "Build one versioned read-only Workspace or Project observation through verified Core loaders.",
        "read-only",
        [PATH_ARGUMENT, PROJECT_ARGUMENT, JSON_ARGUMENT],
    ),
    descriptor(
        "studio.serve",
        "aq studio serve <path> [--project ID] [--host HOST] [--port PORT] [--no-open]",
        "Serve the packaged local read-only research observatory until interrupted.",
        "long-running-server",
        [
            PATH_ARGUMENT,
            PROJECT_ARGUMENT,
            argument(
                "host",
                "option",
                "string",
                False,
                "Local bind address; non-loopback binding is an explicit operator choice.",
                default="127.0.0.1",
            ),
            argument(
                "port",
                "option",
                "integer",
                False,
                "Local HTTP port.",
                default=8765,
            ),
            argument(
                "no-open",
                "option",
                "boolean",
                False,
                "Do not open the default browser.",
                default=False,
            ),
        ],
        supports_json=False,
    ),
]
